name: Publish Docker to Private Docker Hub

on:
  push:
    branches: ["master"] # Триггер на коммиты в master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Получаем код репозитория
      - name: Checkout
        uses: actions/checkout@v4

      # Шаг 2: Логинимся в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Шаг 3: Сборка и публикация образа
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            basiliottl/demo-app:latest
            basiliottl/demo-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
